#!/bin/bash
# turn off raspi led strip

# Cloned repo directory.
REPO_DIR="$HOME/Documents/GitHub/pyWalNeopixels"

USER="pi"
IP=192.168.0.25

# This is the user@ipaddr of your raspi.
USER_IP=$USER@$IP

# Replace this with your cloned repo path, must end with /raspi_files/clearPixels.py
STOP_DIR="$REPO_DIR/raspi_files/clearPixels.py"

# Location for files to be copied to raspi. It can be whatever you'd like, as
# the directory will be created when the script is run.
DEST_DIR="/home/$USER/.LEDS"

echo stopping python programs...
ssh $USER_IP "sudo kill \$(ps aux | grep "[c]ycleColors.py" | awk '{print \$2}' | head -1)"

ssh $USER_IP "test -e $DEST_DIR/raspi_files/clearPixels.py"
if [ $? -eq 0 ]; then
  echo raspi files exist, clearing LEDs...
  ssh $USER_IP "sudo python3 $DEST_DIR/raspi_files/clearPixels.py" &
else
  echo files did not exist on raspi, sending with scp...
  echo making destination directory...
  ssh $USER_IP "mkdir $DEST_DIR"

  scp $STOP_DIR $USER_IP:$DEST_DIR/raspi_files

  echo turning off LEDs...
  ssh $USER_IP "sudo python3 $DEST_DIR/raspi_files/clearPixels.py" &
fi

